### ISSUE TITLE
Building from source tarball from releases doesn't work as expected

### ISSUE THREAD

**Issue by damm** [mcuadros/ascode#3]
Hi,

So I tried building from source because I wanted to test this on arm64, and I ran into a problem with `make goldflags` not working without the git repository installed.  

Failure below this line
---

```
cat: .git/HEAD: No such file or directory
<removed a bunch of lines>
go: finding github.com/rogpeppe/go-internal v1.5.2
2020/03/31 00:25:56 repository does not exist
exit status 1
Makefile:83: recipe for target 'goldflags' failed
```

Checking out the repository and using the `v1.0.0` tag works perfectly fine to build.

**Comment by mcuadros** [comment]
As described in the [documentation](https://ascode.run/docs/install/#clone-from-github), to build from source code you need to clone the git repository and run `go install ./...`. Any way you can build from the tarball running `go install ./...` the Makefile is mainly for CI.

**Comment by damm** [comment]
I see your point about the documentation I just expect the source tarball to be able to be used to build a release.   Maybe stop creating a source tarball in your releases?

**Comment by mcuadros** [comment]
As I said, it is valid, just follow the documentation.
